### ISSUE TITLE
provide loging levels or not use this package from go-micro

### ISSUE THREAD

**Issue by vtolstov** [micro/go-log#1]
i like ability to log some messages only for specific levels, for example
Deregistering node
Unsubscribing from topic
this is noise for normal operations, but useful in debug.

But go-micro uses log.Logf, i can set logger via log package, but i can't filter out this messages for normal mode...

**Comment by asim** [comment]
I don't have a solution for this right now. It's unlikely we introduce levels. The library logging is informational. In error case there should be some retune value or it should fatally error.

You can set the logger to disable this output.

**Comment by tigerlee** [comment]
Loging levels are very useful. It's would be great if official provides, or we might use a logger who supports `Log()`, `Fatal()` at least and other levels or write one by ourselves.
